### PR TITLE
Fix types in version init

### PR DESCRIPTION
**Pull request by iurisilvio**
# Description

Fix errors found after mypy merge.

```
roboflow/core/version.py:110: error: Unsupported operand types for in ("str" and "Response")  [operator]
roboflow/core/version.py:110: error: Value of type "Response" is not indexable  [index]
```

It was a small bug that would be triggered only when our API failed.

Minor regression from https://github.com/roboflow/roboflow-python/pull/276.

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested, please provide a testcase or example of how you tested the change?

CI pass.

### CODE REVIEW

**Review by stellasphere — APPROVED** [review]
Better implementation, LGTM!
